"""Offline DPO training using Reward LM-scored preference pairs.

Stage A of the process reward pipeline:
- Uses preference pairs generated by generate_trajectories.py
- No API calls during training (offline)
- Cheaper alternative to online GRPO with process reward
"""

import argparse
import json
from pathlib import Path

import torch
from datasets import Dataset
from peft import LoraConfig
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration
from trl import DPOConfig, DPOTrainer


def load_dpo_dataset(pairs_path: str) -> Dataset:
    """Load DPO pairs into HuggingFace Dataset format."""
    with open(pairs_path) as f:
        pairs = json.load(f)

    records = []
    for pair in pairs:
        records.append({
            "prompt": pair["prompt"],
            "chosen": pair["chosen"],
            "rejected": pair["rejected"],
        })

    return Dataset.from_list(records)


def train_dpo(
    model_name: str = "Qwen/Qwen2.5-VL-7B-Instruct",
    pairs_path: str = "data/processed/dpo_pairs.json",
    output_dir: str = "checkpoints/dpo",
    sft_checkpoint: str | None = None,
    num_epochs: int = 1,
    batch_size: int = 1,
    gradient_accumulation_steps: int = 8,
    learning_rate: float = 5e-7,
    lora_r: int = 16,
    beta: float = 0.1,
    max_length: int = 2048,
    max_prompt_length: int = 512,
):
    """Run DPO training on Reward LM-scored preference pairs."""
    dataset = load_dpo_dataset(pairs_path)
    print(f"DPO training on {len(dataset)} preference pairs")

    processor = AutoProcessor.from_pretrained(model_name, trust_remote_code=True)

    # Load base model (optionally from SFT/GRPO checkpoint)
    if sft_checkpoint:
        from peft import PeftModel
        base_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            model_name, torch_dtype=torch.bfloat16,
            attn_implementation="flash_attention_2", trust_remote_code=True,
        )
        model = PeftModel.from_pretrained(base_model, sft_checkpoint)
        model = model.merge_and_unload()
    else:
        model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
            model_name, torch_dtype=torch.bfloat16,
            attn_implementation="flash_attention_2", trust_remote_code=True,
        )

    peft_config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_r * 2,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        task_type="CAUSAL_LM",
    )

    training_args = DPOConfig(
        output_dir=output_dir,
        num_train_epochs=num_epochs,
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        learning_rate=learning_rate,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        gradient_checkpointing=True,
        beta=beta,
        max_length=max_length,
        max_prompt_length=max_prompt_length,
        logging_steps=10,
        save_strategy="epoch",
        save_total_limit=3,
        report_to="wandb",
        run_name="vlm-rl-dpo",
        remove_unused_columns=False,
    )

    trainer = DPOTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        peft_config=peft_config,
        processing_class=processor,
    )

    trainer.train()
    trainer.save_model(output_dir)
    processor.save_pretrained(output_dir)
    print(f"DPO model saved to {output_dir}")


def main():
    parser = argparse.ArgumentParser(description="DPO training with Reward LM pairs")
    parser.add_argument("--model", type=str, default="Qwen/Qwen2.5-VL-7B-Instruct")
    parser.add_argument("--pairs-path", type=str, default="data/processed/dpo_pairs.json")
    parser.add_argument("--output-dir", type=str, default="checkpoints/dpo")
    parser.add_argument("--sft-checkpoint", type=str, default=None)
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--grad-accum", type=int, default=8)
    parser.add_argument("--lr", type=float, default=5e-7)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--beta", type=float, default=0.1)
    args = parser.parse_args()

    train_dpo(
        model_name=args.model,
        pairs_path=args.pairs_path,
        output_dir=args.output_dir,
        sft_checkpoint=args.sft_checkpoint,
        num_epochs=args.epochs,
        batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        lora_r=args.lora_r,
        beta=args.beta,
    )


if __name__ == "__main__":
    main()
